RegistroErrores/config/routes.rb
Rails.application.routes.draw do
  
  post 'information_error/generate_pdf'
  resources :programming_errors
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  #admnistrators
  get "/data_users", to: "users/administrators#index"
  get "/data_users/new", to: "users/administrators#new"
  get "/data_users/:id/edit(.:format)", to: "users/administrators#edit"
  post "/data_users/create", to: "users/administrators#create"
  post "/data_users/update", to: "users/administrators#update"
  delete "/data_users/:id(.:format)", :to => "users/administrators#destroy"
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RegistroErrores/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RegistroErrores/app/models/programming_error.rb
class ProgrammingError < ApplicationRecord
	#search_field [:message, :cause,:title,:code]
	#quest_search_on :message, :cause, :title, :code
  #search_option :anywhere
  include PgSearch
  pg_search_scope :search_by_information, against: [:message, :cause,:title,:code], using: :tsearch

  belongs_to :user
end

RegistroErrores/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :programming_errors
end

RegistroErrores/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

RegistroErrores/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

RegistroErrores/app/controllers/information_error_controller.rb
class InformationErrorController < ApplicationController
  def generate_pdf
  	@programming_errors = ProgrammingError.all

    require "prawn/table"
    require "prawn"

    Prawn::Document.generate("information.pdf") do |pdf|
      table_data = Array.new
      table_data << ["Titulo", "Autor"]
      @programming_errors.each do |p|
        table_data << [p.title, p.user.email]
      end
      pdf.table(table_data, :width => 500, :cell_style => { :inline_format => true })
    end

    ApplicationMailer.welcome(current_user.email).deliver

    redirect_to programming_errors_path, notice: 'Pdf was successfully created.' 
  end
end

RegistroErrores/app/controllers/programming_errors_controller.rb
class ProgrammingErrorsController < ApplicationController
  before_action :set_programming_error, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /errors
  # GET /errors.json
  def index
    #@programming_errors = ProgrammingError.search_programming_error("")
    @search_text = params[:search]
    #puts "acaaa: ",@search_text
    if @search_text && @search_text != ""
      @programming_errors = ProgrammingError.search_by_information(@search_text)
    else
       @programming_errors = ProgrammingError.all
    end
     
  end

  # GET /errors/1
  # GET /errors/1.json
  def show
  end

  # GET /errors/new
  def new
    @programming_error = ProgrammingError.new
  end

  # GET /errors/1/edit
  def edit
  end

  # POST /errors
  # POST /errors.json
  def create

    @programming_error = current_user.programming_errors.new(programming_error_params)

    respond_to do |format|
      if @programming_error.save
        format.html { redirect_to @programming_error, notice: 'Error was successfully created.' }
        format.json { render :show, status: :created, location: @programming_error }
      else
        format.html { render :new }
        format.json { render json: @programming_error.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /errors/1
  # PATCH/PUT /errors/1.json
  def update

    if current_user.tipo == "administrador" || current_user.id == @programming_error.user.id
      respond_to do |format|
        if @programming_error.update(programming_error_params)
          format.html { redirect_to @programming_error, notice: 'Error was successfully updated.' }
          format.json { render :show, status: :ok, location: @programming_error }
        else
          format.html { render :edit }
          format.json { render json: @programming_error.errors, status: :unprocessable_entity }
        end
      end
    else

    end

    
  end

  # DELETE /errors/1
  # DELETE /errors/1.json
  def destroy
    if current_user.tipo == "administrador"
      @programming_error.destroy
      respond_to do |format|
        format.html { redirect_to programming_errors_url, notice: 'Error was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programming_error
      @programming_error = ProgrammingError.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def programming_error_params
      params.require(:programming_error).permit(:title,:code, :message, :cause, :solution, :reference)
    end
end

RegistroErrores/app/controllers/users/administrators_controller.rb
class Users::AdministratorsController < ApplicationController
	before_action :set_user, only: [:edit, :update,:destroy]
	before_action :authenticate_user!
	def index
		@users = User.all
	end

	def new
	   @user = User.new
	end

	# GET /users/1/edit
  def edit
  	params[:id] = @user.id
  	puts "ID es1: ",params
  end

	def create
		if current_user.tipo == "administrador"
			@user = User.new(user_params)

			respond_to do |format|
		    if @user.save
		        format.html { redirect_to data_users_path, notice: 'Se creó la cuenta existosamente.' }   
		    else
		        format.html { render :new }
		   end
			end
		else

		end

		
	end

	def destroy
		@user.destroy
	  respond_to do |format|
	    format.html { redirect_to "/data_users", notice: 'Se eliminó el usuario.' }
	  end
	end

	def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to data_users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  	private

  	def set_user
  		puts "ID es: ",params
      @user = User.find(params[:id])
    end

	    # Never trust parameters from the scary internet, only allow the white list through.
		def user_params
      params.require(:user).permit(:name,:last_name,:nick_name, :email, :password, :password_confirmation,:tipo)
    end

end

RegistroErrores/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    # add custom create logic here
    @user = User.new(sign_up_params)

    #@user.tipo = "normal"

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'Se creó existosamente la cuenta.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    super
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def sign_up_params
    puts "Estos son los paremetros: "
    puts params
    params.require(:user).permit(:name,:last_name,:nick_name, :email, :password, :password_confirmation)
  end
end 

RegistroErrores/app/helpers/application_helper.rb
module ApplicationHelper
end

RegistroErrores/app/helpers/home_helper.rb
module HomeHelper
end

RegistroErrores/app/helpers/information_error_helper.rb
module InformationErrorHelper
end

RegistroErrores/app/helpers/programming_errors_helper.rb
module ProgrammingErrorsHelper
end

RegistroErrores/app/views/home/index.html.erb
<div class="container">
	<h1>Página de inicio de la aplicación.</h1>
</div>

RegistroErrores/app/views/information_error/generate_pdf.html.erb
<h1>InformationError#generate_pdf</h1>
<p>Find me in app/views/information_error/generate_pdf.html.erb</p>

RegistroErrores/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bitacora de errores</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>

  <body>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Bitacora de errores", root_path, class:"navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li  class="<%= 'active' if params[:controller] == 'home' %>" ><%= link_to "Inicio", root_path %></li>
          <% if signed_in?%>
          <li class="<%= 'active' if params[:controller] == 'errors' %> " ><a href="/programming_errors/">Errores</a></li>
            <% if current_user.tipo == "administrador"%>
              <li class="<%= 'active' if params[:controller] == 'users#administrators' %> " ><a href="/data_users/">Usuarios</a></li>
            <% end %>
          <% end %>
        </ul>
        <% if signed_in?%>
        <%= form_tag programming_errors_path, class:"navbar-form navbar-left",method: :get do %>
          <div class="input-group">
            <%= text_field_tag :search,params[:search],placeholder: "Buscar",class:"form-control"%>
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
              </button>
            </div>
          </div>
        <% end %>
        <% end %>
        <% if signed_in?%>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/users/sign_out" data-method="delete"><span class="glyphicon glyphicon-log-in"></span> Cerrar Sesión</a>
           </li>
          </ul>
           
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li class="<%= 'active' if request.original_url == request.base_url+"/users/sign_in" %> "><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Inicio de Sesión</a></li>
            <li class="<%= 'active' if request.original_url == request.base_url+"/users/sign_up" %> "><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Registro</a></li>
          </ul>
        <% end %>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

RegistroErrores/app/views/programming_errors/_form.html.erb
<%= form_with(model: programming_error, local: true) do |form| %>
  <% if programming_error.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(programming_error.errors.count, "error") %> prohibited this error from being saved:</h2>

      <ul>
      <% programming_error.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="field">
    <%= form.label :cause %>
    <%= form.text_field :cause %>
  </div>

  <div class="field">
    <%= form.label :solution %>
    <%= form.text_field :solution %>
  </div>

  <div class="field">
    <%= form.label :reference %>
    <%= form.text_field :reference %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RegistroErrores/app/views/programming_errors/edit.html.erb
<h1>Editing Error</h1>

<%= render 'form', programming_error: @programming_error %>

<%= link_to 'Show', @programming_error %> |
<%= link_to 'Back', programming_errors_path %>

RegistroErrores/app/views/programming_errors/index.html.erb
<div class="container">
  <h1>Errores</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Código</th>
      <th>Autor</th>
      <th>Fecha de publicación</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @programming_errors.each do |programming_error| %>
      <tr>
        <td><%= link_to programming_error.title, programming_error %></td> 
        <td><%= programming_error.code %></td>
        <td><%= programming_error.user.nick_name %></td>
        <td><%= programming_error.created_at.in_time_zone("Central America").to_s(:long)%></td>
        <% if current_user.tipo == "administrador"%>
          <td><%= link_to 'Edit', edit_programming_error_path(programming_error) %></td>
          <td><%= link_to 'Destroy', programming_error, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Error', new_programming_error_path%>

<%= link_to 'Generar pdf', "/information_error/generate_pdf/", method: :post , data: { confirm: 'Are you sure?'} %>
</div>

RegistroErrores/app/views/programming_errors/new.html.erb
<h1>New Error</h1>

<%= render 'form', programming_error: @programming_error %>

<%= link_to 'Back', programming_errors_path %>

RegistroErrores/app/views/programming_errors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @programming_error.title %>
</p>

<p>
  <strong>Code:</strong>
  <%= @programming_error.code %>
</p>

<p>
  <strong>Message:</strong>
  <%= @programming_error.message %>
</p>

<p>
  <strong>Cause:</strong>
  <%= @programming_error.cause %>
</p>

<p>
  <strong>Solution:</strong>
  <%= @programming_error.solution %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @programming_error.reference %>
</p>

<p>
  <strong>User:</strong>
  <%= @programming_error.user %>
</p>

<%= link_to 'Atras', programming_errors_path %>

RegistroErrores/app/views/users/administrators/edit.html.erb
<%= form_tag data_users_update_path(:id => @user.id),method: :post do %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= label_tag "Nombre" %>
    <%= text_field_tag "user[name]", @user.name ,required: true%>
  </div>

  <div>
    <%= label_tag "Apellidos" %>
    <%= text_field_tag "user[last_name]", @user.last_name ,required: true%>
  </div>

  <div>
    <%= label_tag "Nombre de usuario" %>
    <%= text_field_tag "user[nick_name]", @user.nick_name ,required: true%>
  </div>

  <div>
    <%= label_tag "Correo" %>
    <%= email_field_tag "user[email]", @user.email ,required: true%>
  </div>

  <div>
    <%= label_tag "Tipo" %>
    <%= text_field_tag "user[tipo]", @user.tipo ,required: true%>
  </div>

  <div class="actions">
    <%= submit_tag "Actualizar" %>
  </div>
<% end %>

<%= link_to 'Atras', data_users_path %>

RegistroErrores/app/views/users/administrators/index.html.erb
<% if current_user.tipo == "administrador" %>
<div class="container">
  <h1>Usuarios</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Nickname</th>
        <th>Correo</th>
        <th>Tipo</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.nick_name %></td>
          <td><%= user.email %></td>
          <td><%= user.tipo %></td>
          <td><%= link_to 'Editar', "/data_users/"+(user.id.to_s)+"/edit", method: :get  %></td>
          <td><%= link_to 'Destruir', "/data_users/"+user.id.to_s, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New User', data_users_new_path %>
  <br>
<% else %>

<% end %>
</div>
  

RegistroErrores/app/views/users/administrators/new.html.erb
<%= form_tag "/data_users/create", method: :post do %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= label_tag "Nombre" %>
    <%= text_field_tag "user[name]", @user.name ,required: true%>
  </div>

  <div>
    <%= label_tag "Apellidos" %>
    <%= text_field_tag "user[last_name]", @user.last_name ,required: true%>
  </div>

  <div>
    <%= label_tag "Nombre de usuario" %>
    <%= text_field_tag "user[nick_name]", @user.nick_name ,required: true%>
  </div>

  <div>
    <%= label_tag "Correo" %>
    <%= email_field_tag "user[email]", @user.email ,required: true%>
  </div>

  <div>
    <%= label_tag "Tipo" %>
    <%= text_field_tag "user[tipo]", @user.tipo ,required: true%>
  </div>

  <div>
    <%= label_tag "Contraseña" %>
    <%= password_field_tag "user[password]", @user.password ,required: true%>
  </div>

  <div>
    <%= label_tag "Confirmación de contraseña" %>
    <%= password_field_tag "user[password_confirmation]", @user.password_confirmation ,required: true%>
  </div>

  <div class="actions">
    <%= submit_tag "Registrar" %>
  </div>
<% end %>